### ISSUE TITLE
Movement speed updated when transformed

### ISSUE THREAD

**Issue by shmup** [shmup/dbz-epic-tintin#3]
Each transformation has a movement speed. When you transform, it should update $move_speed to the appropriate speed, and when you die or transform back it should be reset.

This is useful not for autoflight, because that always uses your new movement speed, but when you manually use the fly north alias, which uses the movement speed variable.

**Comment by shmup** [comment]
This is partially implemented. I need to get the displayed text upon your player's death, so that I can trigger on it.

**Comment by doublesbrian** [comment]
Everything goes dark as you lose consciousness! is what happens when you get knocked out due to enemy or fatigue. 

and I believe

 'Name' has been defeated by 'Enemy Name'! 

is the text when you die.

**Comment by shmup** [comment]
I'm curious if there is a more personal one displayed, that isn't sent to the server. If so, I'll use it. Go ahead and die for me! ^^
